INSERT INTO menuItems (name, description, price, calories) VALUES
('Classic Pearl Milk Black Tea', 'Rich and creamy black milk tea infused with delicious chewy pearls.', 6.25, 808),
('Classic Pearl Milk Green Tea', 'Rich and creamy green milk tea infused with delicious chewy pearls.', 6.25, 808),
('Classic Pearl Milk Oolong Tea', 'Rich and creamy oolong milk tea infused with delicious chewy pearls.', 6.25, 808),
('Honey Pearl Milk Black Tea', 'Light and refreshing black milk tea made with honey and chewy pearls.', 6.50, 892),
('Honey Pearl Milk Green Tea', 'Light and refreshing green milk tea made with honey and chewy pearls.', 6.50, 892),
('Honey Pearl Milk Oolong Tea', 'Light and refreshing oolong milk tea made with honey and chewy pearls.', 6.50, 892),
('Coffee Creama', 'A blend of cream and coffee for a balanced coffee experience.', 6.95, 768),
('Coffee Milk Tea w/ Coffee Jelly', 'A blend of black tea and coffee for a balanced taste, with chewy coffee jelly.', 6.75, 584),
('Hokkaido Pearl', 'A milky, toffee-like flavored milk tea that offers a rich and sweet experience.', 6.75, 758),
('Thai Pearl Milk Tea', 'Rich and creamy milk tea infused with distinct Thai flavors and pearls.', 6.75, 980),
('Taro Pearl Milk Tea', 'Taro flavor milk tea, infused with earthy notes and chewy pearls.', 6.75, 964),
('Mango Green Milk Tea', 'Green tea and creamer base with added fruity mango flavor.', 6.95, 602),
('Golden Retriever', 'Black milk tea with a playful mix of chewy pearls and flavor.', 7.00, 753),
('Coconut Pearl Milk Black Tea', 'Coconut flavor black milk tea, infused with earthy tones and chewy pearls.', 7.00, 781),
('Coconut Pearl Milk Green Tea', 'Coconut flavor green milk tea, infused with earthy tones and chewy pearls.', 7.00, 781),
('Classic Black Tea', 'Classic brewed black tea made fresh daily without milk.', 4.95, 216),
('Classic Green Tea', 'Classic brewed green tea made fresh daily without milk.', 4.95, 216),
('Classic Oolong Tea', 'Classic brewed oolong tea made fresh daily without milk.', 4.95, 216),
('Honey Black Tea', 'Freshly brewed black tea with a touch of mild honey sweetness.', 5.20, 262),
('Honey Green Tea', 'Freshly brewed green tea with a touch of mild honey sweetness.', 5.20, 262),
('Honey Oolong Tea', 'Freshly brewed oolong tea with a touch of mild honey sweetness.', 5.20, 262);
